### ISSUE TITLE
Failing to build on nightly

### ISSUE THREAD

**Issue by nelhage** [cuviper/rust-libprobe#11]
I'm getting build errors on Rust nightly, using [this minimal test case](https://gist.github.com/nelhage/553cae9fa5d225630fb01382147c55aa):

```
[nelhage@monolithique:/tmp/probetest]$ cargo +nightly build
   Compiling probetest v0.1.0 (/tmp/probetest)
error[E0660]: malformed inline assembly
 --> main.rs:4:5
  |
4 |     probe!(test_probe, entry);
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: use of deprecated item 'asm': the syntax of asm! will change soon, use llvm_asm! to avoid breakage
 --> main.rs:4:5
  |
4 |     probe!(test_probe, entry);
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(deprecated)]` on by default
  = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0660`.
error: could not compile `probetest`.

To learn more, run the command again with --verbose.
```

I'm seeing this error on a nightly pulled from `rustup` just now, as well as on `nightly-2020-04-08-x86_64-unknown-linux-gnu`, although that doesn't give the warning:
```
[nelhage@monolithique:/tmp/probetest]$ cargo +nightly-2020-04-08-x86_64-unknown-linux-gnu build
   Compiling probetest v0.1.0 (/tmp/probetest)
error[E0660]: malformed inline assembly
 --> main.rs:4:5
  |
4 |     probe!(test_probe, entry);
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0660`.
error: could not compile `probetest`.

To learn more, run the command again with --verbose.
```

**Comment by cuviper** [comment]
Rust is transitioning from the old `asm!` syntax (now `llvm_asm!` -- https://github.com/rust-lang/rust/issues/70173) to a new syntax (https://github.com/rust-lang/rust/issues/72016), and I converted to the new in `probe 0.2`. I doubt that will work on a nightly as old as 2020-04-08, but I don't know why it wouldn't work when you pulled a current nightly. Your reproducer works for me with:

```
rustc 1.45.0-nightly (f93bb2a50 2020-05-25)
binary: rustc
commit-hash: f93bb2a50b37bc8bafe4d960e2afd839eaa854ed
commit-date: 2020-05-25
host: x86_64-unknown-linux-gnu
release: 1.45.0-nightly
LLVM version: 10.0
```

**Comment by cuviper** [comment]
FWIW, I could publish a 0.1 update to use `llvm_asm!` if necessary, but I'm not sure it's needed. There is one downside to the new asm in that it only supports register constraints, which means I had to use `isize` for arguments instead of `i64`, since 32-bit platforms can't generally put `i64` in registers. Previously, those could be stored as memory operands.

**Comment by nelhage** [comment]
Ah, darn, my bad -- I ran a `rustup update` but that seems to have actually gotten a two-week-old build because of some issue related to `rls-preview` and `rustfmt`. Grabbing the actual latest nightly fixes it. Sorry for the noise!
