### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by penberg** [cuviper/rust-libprobe#7]
The example in the following documentation is out of date and does not compile:

https://cuviper.github.io/rust-libprobe/doc/probe/

**Comment by cuviper** [comment]
Ah, yeah, I was originally leaning on rust-ci.org for this, but that's been dead for a while now.  I pushed an update to gh-pages, and I'll go update the other references.

**Comment by cuviper** [comment]
Fixed in 98b71d8fa609044e602c7d67286ffcd26b3cc647.
