### ISSUE TITLE
Using the library in stable rust

### ISSUE THREAD

**Issue by tailhook** [cuviper/rust-libprobe#9]
Is there any chance this kind of library be available for stable rust? It's ugly to use nightly just for adding USDT.

I don't know how this works internally to figure out way on my own. But maybe we can use some attributes like `link_section` for markers (or is it unstable too?). Or just use a piece of C code for embedding asm instead of using `feature(asm)` ?

**Comment by cuviper** [comment]
First off, I'm pleased that someone is still interested in this! :smile:

Unfortunately, I don't see a real path forward without `feature(asm)`.  There's more to it than just declaring a section, especially all the *content* of that note.  Some of it could be generated in a static byte array, but the probe address currently references a asm label.  I don't know how you'd do that without the assembler and linker's cooperation.

You could do a bit of external C code already, using the original sdt.h in a function that Rust can call as FFI, but that means having a function call for every probe even when disabled.  Maybe LTO could inline that -- I'm not sure.

There's an alternate [rust-usdt](https://github.com/Fiedzia/rust-usdt) which is a compiler plugin instead, but that's a nightly feature too, and it still needs `feature(asm)`.  See also their post on internals:
https://internals.rust-lang.org/t/tracing-in-rust-with-uprobes/4756

**Comment by No9** [comment]
@tailhook FYI I put together a sample to show how you wrap a C based USDT probe into a rust stable build
https://github.com/No9/rust-usdt-helloworld 
It works but the flow has a few edges.

**Comment by cuviper** [comment]
Per #15, this now works on beta without unstable features, so it will be stable in Rust 1.59!
